# Glassflow ETL chart values (minimal) pointing to Kafka topics from Collector



api:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

ui:
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

glassflow-operator:
  controllerManager:
    manager:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 512Mi
    
  glassflowComponents:
    ingestor:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 512Mi

    join:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 512Mi
    
    sink:
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
